[package]
name = "matasano"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.1"
base64 = "0.13.0"
cipher = "0.4.3"
crypto-common = "0.1.3"
hex = "0.4.3"
inout = "0.1.2"